name: "Release"
on: 
   push:
       tags:       
         - '*'

jobs:

  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
            submodules: recursive
      - run: sudo add-apt-repository -y ppa:sunderme/texstudio

      - run: sudo apt install texlive-latex-extra
      - run: echo $PWD
      - run: ls -al ./
      - run: ls -al ../
      - run: sed -i 's/VERSIONNUMBER/${{  github.ref_name }}/g' LSScopeSequence.tex
      - run: pdflatex -jobname=LSScopeSequence-${{  github.ref_name }} LSScopeSequence.tex
      - run: ls -al .
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
              draft: false
              prerelease: false
              release_name: ${{ steps.get_version.outputs.VERSION }}
              tag_name: ${{ github.ref }}
        env:
              GITHUB_TOKEN: ${{ github.token }}
              

      - name: Upload Keywords
        uses: actions/upload-release-asset@v1
        env:
              GITHUB_TOKEN: ${{ github.token }}
        with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: LSScopeSequence-${{  github.ref_name }}.pdf
              asset_name: LSScopeSequence-${{  github.ref_name }}.pdf
              asset_content_type: application/binary
